@hostLocal=http://localhost:8866

### /v1/chat/completions
POST {{hostLocal}}/v1/chat/completions
Content-Type: application/json
Authorization: Bearer br-WP4elEV2VzZ7AGYsNEfvSrKPaQcZ6

{
  "model": "claude-3-sonnet",
  "messages": [
    {
      "role": "user",
      "content": "ping"
    }
  ],
  "stream": true,
  "max_tokens": 4096
}



### add a user
POST {{hostLocal}}/admin/api-key/apply
Content-Type: application/json
Authorization: Bearer br_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

{
  "name": "jack",
  "group_id": 1,
  "role": "user",
  "email": "cloudbeer@gmail.com",
  "month_quota": 10
}


### add an admin
POST {{hostLocal}}/admin/api-key/apply
Content-Type: application/json
Authorization: Bearer br-WP4elEV2VzZ7AGYsNEfvSrKPaQcZ6

{
  "name": "rob",
  "group_id": 1,
  "role": "admin",
  "email": "cloudbeer@gmail.com",
  "month_quota": 20
}


### use other key
POST {{hostLocal}}/admin/api-key/apply
Content-Type: application/json
Authorization: Bearer br-uKUzZG3y1N9WB8qyhWCEVQ2ljHeSk

{
  "name": "rob2",
  "group_id": 1,
  "role": "user",
  "email": ""
}

### list api key
GET {{hostLocal}}/admin/api-key/list?q=&limit=10&offset=
Content-Type: application/json
Authorization: Bearer br_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

### api key detail
GET {{hostLocal}}/admin/api-key/detail/2
Content-Type: application/json
Authorization: Bearer br_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

### recharge
POST {{hostLocal}}/admin/api-key/recharge
Content-Type: application/json
Authorization: Bearer br_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

{
  "api_key": "br-WP4elEV2VzZ7AGYsNEfvSrKPaQcZ6",
  "balance": 0.23
}

### recharge
POST {{hostLocal}}/admin/api-key/recharge
Content-Type: application/json
Authorization: Bearer br_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

{
  "id": 2,
  "balance": 0.23
}

### get pay history
GET {{hostLocal}}/admin/payment/list?key_id=
Authorization: Bearer br_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

### update api key fields
POST {{hostLocal}}/admin/api-key/update
Content-Type: application/json
Authorization: Bearer br_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

{
  "id": 2,
  "month_quota": 10
}


### session detail
GET {{hostLocal}}/admin/session/detail?id=1
Authorization: Bearer br_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


### ssesion list
GET {{hostLocal}}/admin/session/list?key_id=
Content-Type: application/json
Authorization: Bearer br_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


### thread list
GET {{hostLocal}}/admin/thread/list?offset=0&q=&limit=100
Content-Type: application/json
Authorization: Bearer br_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

### thread detail
GET {{hostLocal}}/admin/thread/detail/8
Content-Type: application/json
Authorization: Bearer br_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


### My Key Info
GET {{hostLocal}}/user/api-key/mine
Content-Type: application/json
Authorization: Bearer br-WP4elEV2VzZ7AGYsNEfvSrKPaQcZ6


### My session
GET {{hostLocal}}/user/session/list
Content-Type: application/json
Authorization: Bearer br-XRj9hvd6zsxQo3AIUqMBYqYQemKZK

### My session
GET {{hostLocal}}/user/thread/list
Content-Type: application/json
Authorization: Bearer br_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


### 

GET http://34.223.23.146:8866/user/thread/detail/2
Content-Type: application/json
Authorization: Bearer br-k8P2Savqql5XpcuKRZqoxAxvLNbDL
